spring:
  application:
    name: workflow
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/workflow-db
    username: richard
    password: 5565
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false




